camera:
  type: device
  index: 1
  backend: msmf
  width: 1280
  height: 720
  fps: 30
models:
  device: auto
  dog_detector: yolo11s.pt
  hazard_detector: yoloe-11s-seg.pt
  clip_source: openai-clip
  clip_openai_name: ViT-B/32
  clip_model: ViT-B-32
  clip_pretrained: laion2b_s34b_b79k
  vlm: moondream
  ollama_url: http://localhost:11434
hazards:
  battery: 3
  phone charger cable: 3
  electric cord: 3
  medicine pill: 3
  pill bottle: 1
  plastic bag: 2
  chocolate: 3
  slipper: 2
  shoe: 2
  sock: 2
  remote control: 2
  trash can: 2
  toy: 1
  comb: 2
  hairbrush: 2
  pen: 2
  bottle cap: 2
  earphones: 3
  coin: 3
  dog collar: 0
  dog paw: 0
  dog: 0
  pillow: 0
  blanket: 0
  person: 0
  chair: 0
actions:
- sleeping
- lying down
- sitting
- standing
- walking
- sniffing the floor
- chewing something
- eating
- digging
- scratching itself
- scratching furniture
- jumping on furniture
- licking itself
zones:
- name: Bed 1
  type: bed
  points:
  - - 0.2484
    - 0.2375
  - - 0.7422
    - 0.3556
  - - 0.9484
    - 0.3819
  - - 0.9852
    - 0.9694
  - - 0.0297
    - 0.7042
risk:
  persist_seconds: 1.0
  cooldown_warning: 20
  cooldown_danger: 5
  last_seen_memory_seconds: 5
  muzzle_near_px: 60
alerts:
  voice: true
  do_not_disturb: false
  owner_voice_clip: ''
  speak_vlm: true
  toast: true
  voice_name: Microsoft Zira Desktop - English (United States)
  voice_rate: 1
detect:
  dog_conf: 0.18
  imgsz: 960
  hazard_conf: 0.25
qa:
  hands_free: false
ui:
  theme: light
behaviors:
  chewing:
    level: 2
    seconds: 5
  long_chewing:
    level: 3
    seconds: 15
  nose_down:
    level: 2
    seconds: 6
  rough_play:
    level: 2
    seconds: 3
  fighting:
    level: 2
    seconds: 5
  digging:
    level: 2
  scratching furniture:
    level: 2
  jumping on furniture:
    level: 0
  sniffing the floor:
    level: 1
  licking itself:
    level: 1
  scratching itself:
    level: 0
  walking:
    level: 0
  standing:
    level: 0
  sitting:
    level: 0
  lying down:
    level: 0
  sleeping:
    level: 0
